name: Build

on:
  push:
    branches: [ kivy-ios ]
  pull_request:
    branches: [ kivy-ios ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: sh Scripts/ci.sh
      id: script
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.script.outputs.tag }}"
        files: 'kivy-ios/*.xcframework.zip'
